# Numpy Library - Array Creations and Modifications

#### Index
1. Basics
2. Array Creation
3. Dimensions in Arrays
4. Array Properties
5. Numpy Data Types
6. Accessing Array Elements
5. Array Modifications

### Basics
- NumPy is used for working with arrays.
- NumPy is short for "Numerical Python".
- It also has functions for working in domain of linear algebra, fourier transform, and matrices.
- NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
- Some other libraries will be working on Numpy for fast computation. Such as Matplotlib, etc.

#### Why is NumPy Faster Than Lists?
- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
- This behavior is called locality of reference in computer science.
- This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

#### Which Language is NumPy written in?
- NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

In [1]:
import numpy

print(numpy.__version__)

1.21.5


#### Numpy memory usage
- Numpy doesn't use huge memory as typical python datatypes.
- for eg, "x=5" requires only 3 bytes in numpy, whereas python uses as mush as 20 bytes.
- In numpy we can specify size of each charachter in datatypes.

In [4]:
import numpy as np
np.int32

numpy.int32

### Array Creation
#### np.array()

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [34]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr, type(arr), sep='\n')

[1 2 3 4 5]
<class 'numpy.ndarray'>


#### arange
* Format = **arange(start:end:step)**

In [35]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [36]:
a = np.arange(2, 10, 2)
a

array([2, 4, 6, 8])

#### linspace
* Format = **linspace(start:end:count)**

In [37]:
b = np.linspace(0, 10, 15)
b

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

### Dimensions in Arrays
* Function **shape** is used to identify the shape of the array.
* Function **ndim** is used to identify the dimension of the array.

#### 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [9]:
import numpy as np

arr = np.array(42)

print(arr, arr.shape, arr.ndim, arr.size, sep="\n")

42
()
0
1


#### 1-D Arrays

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr, arr.shape, arr.ndim, arr.size, sep="\n")

[1 2 3 4 5]
(5,)
1
5


#### 2-D Arrays
NumPy has a whole sub module dedicated towards matrix operations called **numpy.mat**.

In [11]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr, arr.shape, arr.ndim, arr.size, sep="\n")

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6


#### 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.<br>
These are often used to represent a 3rd order tensor.

In [16]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr,"", arr.shape, arr.ndim, arr.size, sep="\n")

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]

(2, 2, 3)
3
12


#### Check Number of Dimensions?
NumPy Arrays provides the "**ndim**" attribute that returns an integer that tells us how many dimensions the array have.

In [8]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


#### Higher Dimensional Arrays
An array can have any number of dimensions.
When the array is created, you can define the number of dimensions by using the "**ndmin**" argument.

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5], ndmin=5)

print(arr)
print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5


### Array Properties
* Type of array = **type**
* Array Shape = **shape**
* Number of dimensions = **ndim**
* Total number of elements = **size**
* Element type = **dtype**

### Numpy Data Types
* by using **dtype** function, we can identify type of a variable.

In [2]:
import numpy as np

In [2]:
a = np.array(1)
print(a)
print(a.dtype)

1
int32


In [3]:
b = np.array(1, dtype = np.float)
print(b)
print(b.dtype)

1.0
float64


C:\Users\abdur\AppData\Local\Temp\ipykernel_18860\3786019393.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b = np.array(1, dtype = np.float)


### Access Array Elements
- Array Slicing: **[start:end:step]**.

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[3:])

[4 5 6 7]


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])  # negative slicing

[5 6]


In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1::2])  # using step

[2 4 6]


#### Access 2-D Arrays

In [12]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [14]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[[0, 1], 1:4])

[[2 3 4]
 [7 8 9]]


#### Access 3-D Arrays

In [17]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0, 1, 2])  # Access the third element of the second array of the first array

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


#### Negative Indexing

In [16]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])  # last element in the second row

Last element from 2nd dim:  10


### Array Modifications

In [17]:
import numpy as np

In [19]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a, "", a.ndim, a.shape, sep="\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]]

2
(3, 3)


In [20]:
a[1] = [10, 10, 10]
a

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [22]:
a[:, 1] = 11
a

array([[ 1, 11,  3],
       [10, 11, 10],
       [ 7, 11,  9]])