# Numpy Library - Operations on Arrays

#### Index
1. Arithmetic
2. Compound Assignment
3. Boolean 
4. Vector operations

# Arithmetic
#### Addition

In [2]:
import numpy as np

In [10]:
# Scalar + Scalar
a = np.array(4)
b = np.array(5)
print("a: ", a)
print("b: ", b)
print("a + B: ", a + b)

a:  4
b:  5
a + B:  9


In [11]:
# 1D array + 1D array
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])
print("a: ", a)
print("b: ", b)
print("a + B: ", a + b)

a:  [1 2 3 4]
b:  [1 2 3 4]
a + B:  [2 4 6 8]


In [13]:
# 1D array + Scalar
# This process is called broadcasting
a = np.arange(4)
b = np.array(10)
print("a: ", a)
print("b: ", b)
print("a + B: ", a + b)

a:  [0 1 2 3]
b:  10
a + B:  [10 11 12 13]


In [14]:
# 2D array + 2D array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2, 3], [4, 5, 6]])
print("a: ", a)
print("b: ", b)
print("a + B: ", a + b)

a:  [[1 2 3]
 [4 5 6]]
b:  [[1 2 3]
 [4 5 6]]
a + B:  [[ 2  4  6]
 [ 8 10 12]]


In [15]:
# 2D array + 1D array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])
print("a: ", a)
print("b: ", b)
print("a + B: ", a + b)

a:  [[1 2 3]
 [4 5 6]]
b:  [1 2 3]
a + B:  [[2 4 6]
 [5 7 9]]


In [16]:
# 2D array + Scalar
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array(10)
print("a: ", a)
print("b: ", b)
print("a + B: ", a + b)

a:  [[1 2 3]
 [4 5 6]]
b:  10
a + B:  [[11 12 13]
 [14 15 16]]


#### Multiplication

In [18]:
# Scalar * Scalar
a = np.array(4)
b = np.array(5)
print("a: ", a)
print("b: ", b)
print("a * B: ", a * b)

a:  4
b:  5
a * B:  20


In [19]:
# 1D array * 1D array
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])
print("a: ", a)
print("b: ", b)
print("a * B: ", a * b)

a:  [1 2 3 4]
b:  [1 2 3 4]
a * B:  [ 1  4  9 16]


In [20]:
# 1D array * Scalar
a = np.arange(4)
b = np.array(10)
print("a: ", a)
print("b: ", b)
print("a * B: ", a * b)

a:  [0 1 2 3]
b:  10
a * B:  [ 0 10 20 30]


In [21]:
# 2D array * 2D array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2, 3], [4, 5, 6]])
print("a: ", a)
print("b: ", b)
print("a * B: ", a * b)

a:  [[1 2 3]
 [4 5 6]]
b:  [[1 2 3]
 [4 5 6]]
a * B:  [[ 1  4  9]
 [16 25 36]]


In [22]:
# 2D array * 1D array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])
print("a: ", a)
print("b: ", b)
print("a * B: ", a * b)

a:  [[1 2 3]
 [4 5 6]]
b:  [1 2 3]
a * B:  [[ 1  4  9]
 [ 4 10 18]]


In [23]:
# 2D array * Scalar
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array(10)
print("a: ", a)
print("b: ", b)
print("a * B: ", a * b)

a:  [[1 2 3]
 [4 5 6]]
b:  10
a * B:  [[10 20 30]
 [40 50 60]]


# Compound Assignment

In [17]:
a = np.array([1, 2, 3])
print(a)
a += 10
print(a)

[1 2 3]
[11 12 13]


# Boolean Operations

In [1]:
import numpy as np

In [2]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [3]:
print(a > 2)

[False False False  True  True]


# Vector Operations

### Vector Addition
![numpy_operations_1](https://github.com/abdurahimank/Statistics-using-Python/blob/main/images/numpy_operations_1.png?raw=true)

In [9]:
import numpy as np
u = np.array([1, 0])
v = np.array([0, 1])
z = u + v
print(u, v, z, type(z), sep="\n")

[1 0]
[0 1]
[1 1]
<class 'numpy.ndarray'>


In [6]:
u = np.eye(3)
z = u + u
z

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

### Vector Subtraction

In [7]:
import numpy as np
u = np.array([1, 0])
v = np.array([0, 1])
z = u - v
print(u, v, z, type(z), sep = "\n")

[1 0]
[0 1]
[ 1 -1]
<class 'numpy.ndarray'>


### Scalar Multiplication
![numpy_operations_2](https://github.com/abdurahimank/Statistics-using-Python/blob/main/images/numpy_operations_2.png?raw=true)

In [8]:
u = np.array([1, 2])
z = 2 * u
print(u, z, sep="\n")

[1 2]
[2 4]


#### Dot Product
![numpy_operations_3](https://github.com/abdurahimank/Statistics-using-Python/blob/main/images/numpy_operations_3.png?raw=true)

In [10]:
u = np.array([1, 2])
v = np.array([3, 1])
z = np.dot(u, v)
print(u, v, z, type(z), sep = "\n")

[1 2]
[3 1]
5
<class 'numpy.int32'>


In [8]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
print(a)
print(b)
np.dot(a, b)

[[1, 0], [0, 1]]
[[4, 1], [2, 2]]


array([[4, 1],
       [2, 2]])

#### Cross Product

In [7]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[4,5,6], [1,2,3]])
print(x)
print(y)
np.cross(x, y)

[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [1 2 3]]


array([[-3,  6, -3],
       [ 3, -6,  3]])