# Numpy Library - Statistics Tools

#### Index
1. Mean, Median and Mode
2. 

### Cetral Tendency
* mean
* 

#### 1D array

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])
a.sum()

15

In [3]:
a.mean()

3.0

In [5]:
a.std()

1.4142135623730951

In [6]:
a.var()

2.0

#### 2D array

In [8]:
a = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
print(a)
print(a.sum())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45


In [9]:
print(a.mean())

5.0


In [10]:
print(a.std())

2.581988897471611


In [11]:
print(a.sum(axis=0))

[12 15 18]


In [15]:
print(a.mean(axis=0))

[4. 5. 6.]


In [16]:
print(a.std(axis=0))

[2.44948974 2.44948974 2.44948974]


In [12]:
print(a.sum(axis=1))

[ 6 15 24]


In [14]:
print(a.mean(axis=1))

[2. 5. 8.]


In [17]:
print(a.std(axis=1))

[0.81649658 0.81649658 0.81649658]
